In [7]:
%matplotlib inline
import numpy as np
import pandas as pd
np.random.seed(100)

In [8]:
# 1) How likely is it that you roll doubles when rolling two 
# dice?

nrows = 100_000 # set nrows to number of simulations
ncols = 2       # set ncolumns to number of dice rolled in each simulation

# create data frame with each row representing a simulation and each column representing a dice roll in the simulation
rolls = np.random.choice([1, 2, 3, 4, 5, 6], nrows * ncols).reshape(nrows, ncols) 

df = pd.DataFrame(rolls)

# add double columnn
df['doubles'] = df[0] == df[1]

# get mean of doubles column
# format and print results
odds_of_doubles = int(round(df.doubles.mean(),2) * 100)

print(f'The odds of rolling doubles on two fair 6 sided dice are {odds_of_doubles}%')

The odds of rolling doubles on two fair 6 sided dice are 17%


In [3]:
# 2) If you flip 8 coins, what is the probability of getting 
# exactly 3 heads? What is the probability of getting more 
# than 3 heads?

n_trials = nrows = 10_000
f_coins = ncols = 8

flip = np.random.choice([0, 1], n_trials * f_coins).reshape(nrows, ncols)
flip

flips = pd.DataFrame(flip)
flips.columns = ["Coin_1", "Coin_2", "Coin_3", "Coin_4", "Coin_5", "Coin_6", "Coin_7", "Coin_8"]
flips

flips["n_heads"] = flips.sum(axis=1)
flips.head()


# probability of getting exactly 3 heads
(flips.n_heads == 3).mean()

0.2215

In [9]:
flips.head()

Coin_1  Coin_2  Coin_3  Coin_4  Coin_5  Coin_6  Coin_7  Coin_8  n_heads
0       1       0       0       1       1       1       0       0        4
1       0       0       1       1       1       0       1       1        5
2       0       0       1       0       1       0       0       0        2
3       0       0       1       1       1       1       0       0        4
4       1       1       1       0       0       0       1       1        5

In [23]:
# probability of getting more than 3 heads
(flips.n_heads > 3).mean()

0.633

In [24]:
# Another why to answer this question 2:
nrows = 100_000 # set rows to number of simulations
ncols = 8       # set columns to number of random events in each simulation

# create array
rolls = np.random.choice([True, False], nrows * ncols).reshape(nrows, ncols)

# create dataframe
df = pd.DataFrame(rolls)

# add calculation columnns
df['number_of_heads'] = df.sum(axis=1)
df['exactly_three_heads'] = df.number_of_heads == 3
df['three_or_more_heads'] = df.number_of_heads >= 3

# get mean of calculation True/False columns
# format and print results
odds_of_three_heads = int(round(df.exactly_three_heads.mean(),2) * 100)
odds_of_three_or_more_heads = int(round(df.three_or_more_heads.mean(),2) * 100)

print(f'The odds of getting exactly three heads when flipping five coins is {odds_of_three_heads}%')
print(f'The odds of gettng three or more heads in the same five flips is {odds_of_three_or_more_heads}%')

The odds of getting exactly three heads when flipping five coins is 22%
The odds of gettng three or more heads in the same five flips is 86%


In [26]:
# 3) There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 
# Assuming that Codeup randomly selects an alumni to put on a billboard, 
# what are the odds that the two billboards I drive past both have data science students on them?

n_trials = nrows = 10_000
f_stu = ncols = 2

b_board = np.random.choice(["Web_dev", "Web_dev", "Web_dev", "DS"], n_trials * f_stu).reshape(nrows, ncols)
b_board

b_boards = pd.DataFrame(b_board)
b_boards.columns = ["bill_board1", "bill_board2"]

((b_boards.bill_board1 == "DS")  & (b_boards.bill_board2 == "DS")).mean()



0.056

In [27]:
# Another why to answer this question 3:
nrows = 100_000 # set rows to number of simulations
ncols = 2       # set columns to number of bilboards in each simulation

# create data frame with each row representing a simulation and each column representing a bilboard in the simulation
rolls = np.random.choice(["DS","WEB","WEB","WEB"], nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(rolls)

# add calculation columnn
df['both_ds'] = (df[0] == "DS") & (df[1] == "DS")

# get mean of calculation True/False columns
# format and print results
both_ds = int(round(df.both_ds.mean(),2) * 100)

print(f'The odds of both billboards being Data Science are {both_ds}%')

The odds of both billboards being Data Science are 6%


In [ ]:
# 4) Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day 
# from the snack vending machine. If on monday the machine is restocked with 17 poptart 
# packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? 
# (Remember, if you have mean and standard deviation, use the np.random.normal)



In [28]:
nrows = 10_000 # set rows to number of simulations
ncols = 5       # set columns to number of days in each simulation

In [32]:
# create array with each row representing a simulation and each column representing a day in the simulation
poptart = np.random.normal(3, 1.5, nrows * ncols).astype(int).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(rolls)
df.head()


0  1  2  3  4
0  2  1  0  2  3
1  1  2  4  1  2
2  3  2  1  2  2
3  4  3  1  1  1
4  4  3  2  2  4

In [38]:
poptart.min()

-3

In [35]:
# add calculation columnns
df['total_pop_tarts_bought'] = df.sum(axis=1)
df['pop_tarts_remain'] = df['total_pop_tarts_bought'] < 17
df.head()

0  1  2  3  4  total_pop_tarts_bought  pop_tarts_remain
0  2  1  0  2  3                       8              True
1  1  2  4  1  2                      10              True
2  3  2  1  2  2                      10              True
3  4  3  1  1  1                      10              True
4  4  3  2  2  4                      15              True

In [36]:
df['pop_tarts_remain'].mean()

0.8784

In [37]:
# get mean of calculation True/False columns
# format and print results
tarts = int(round(df['pop_tarts_remain'].mean(),2) * 100)


print(f'The odds of being able to by a PopTart in the afternoon on friday are {tarts}%')

The odds of being able to by a PopTart in the afternoon on friday are 88%


In [ ]:
# 5) Men have an average height of 178 cm and standard deviation of 
# 8cm. Women have a mean of 170, sd = 6cm. If a man and woman are 
# chosen at random, P(woman taller than man)?

In [45]:
# create arrays of veriables
male_heights = np.random.normal(178, 8, 100_000)
female_heights = np.random.normal(170, 6, 100_000)

In [46]:
male_heights

array([165.93534663, 172.37028136, 170.36354442, ..., 182.23131911,
       186.95939774, 167.76163569])

In [47]:
female_heights

array([173.42379183, 174.4145254 , 179.84359875, ..., 165.67737229,
       169.96559128, 170.8703171 ])

In [49]:
# convert array to data frame
df = pd.DataFrame({"male_heights" : male_heights,
                   "female_heights" : female_heights})

df.head()

male_heights  female_heights
0    165.935347      173.423792
1    172.370281      174.414525
2    170.363544      179.843599
3    193.157872      164.662827
4    181.554350      173.911451

In [50]:
# add calculation column
df['female_is_taller'] = df.female_heights > df.male_heights
df.head()


male_heights  female_heights  female_is_taller
0    165.935347      173.423792              True
1    172.370281      174.414525              True
2    170.363544      179.843599              True
3    193.157872      164.662827             False
4    181.554350      173.911451             False

In [51]:
# get mean of female_is_taller
df['female_is_taller'].mean()

0.20989

In [52]:
# get mean of calculation True/False columns
# format and print results
taller_female = int(round(df['female_is_taller'].mean(),2) * 100)

print(f"The probability of a woman, chosen at random, being taller than a man, chosen at random is {taller_female}%")

The probability of a woman, chosen at random, being taller than a man, chosen at random is 21%


In [53]:
# 6) When installing anaconda on a student's computer, there's a 1 in 250 
# chance that the download is corrupted and the installation fails.

# What are the odds that after having 50 students download anaconda, 
# no one has an installation issue? 100 students?

In [54]:
nrows = 100_000 # set rows to number of simulations
ncols = 50      # set columns to number of days in each simulation

In [55]:
# create array with each row representing a simulation and each column representing a student in the simulation

# list with 249 falses and one true
issue_range = [False for r in range(1,250)]
issue_range.append(True)

# create array
installs = np.random.choice(issue_range, nrows * ncols).reshape(nrows, ncols)
installs

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [ True, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [56]:
# convert to data frame
df = pd.DataFrame(installs)
df.head(5)

0      1      2      3      4      5      6      7      8      9   ...  \
0  False  False  False  False  False  False  False  False  False  False  ...   
1  False  False  False  False  False  False  False  False  False  False  ...   
2  False  False  False  False  False  False  False  False  False  False  ...   
3  False  False  False  False  False  False  False  False  False  False  ...   
4  False  False  False  False  False  False  False  False  False  False  ...   

      40     41     42     43     44     45     46     47     48     49  
0  False  False  False  False  False  False  False  False  False  False  
1  False  False  False  False  False  False  False  False  False  False  
2  False  False  False  False  False  False  False  False  False  False  
3  False  False  False  False  False  False  False  False  False  False  
4  False  False  False  False  False  False  False  False  False  False  

[5 rows x 50 columns]

In [57]:
# add calculation columnns
df['has_no_problem'] = df.sum(axis=1) == 0
df.head()

0      1      2      3      4      5      6      7      8      9  ...  \
0  False  False  False  False  False  False  False  False  False  False  ...   
1  False  False  False  False  False  False  False  False  False  False  ...   
2  False  False  False  False  False  False  False  False  False  False  ...   
3  False  False  False  False  False  False  False  False  False  False  ...   
4  False  False  False  False  False  False  False  False  False  False  ...   

      41     42     43     44     45     46     47     48     49  \
0  False  False  False  False  False  False  False  False  False   
1  False  False  False  False  False  False  False  False  False   
2  False  False  False  False  False  False  False  False  False   
3  False  False  False  False  False  False  False  False  False   
4  False  False  False  False  False  False  False  False  False   

   has_no_problem  
0            True  
1            True  
2            True  
3            True  
4            True  

[5 rows x 51 columns]

In [58]:
df['has_no_problem'].mean()

0.8188

In [59]:
# get mean of calculation True/False columns
# format and print results
problems = int(round(df['has_no_problem'].mean(),2) * 100)

print(f'The odds of 100 students dowloading Anaconda without a problem are {problems}%')


The odds of 100 students dowloading Anaconda without a problem are 82%


In [60]:
# What is the probability that we observe an installation issue within 
# the first 150 students that download anaconda?

nrows = 100_000 # set rows to number of simulations
ncols = 150      # set columns to number of students in each simulation

# list with 249 falses and one true
issue_range = [False for r in range(1,250)]
issue_range.append(True)

# create array with each row representing a simulation and each column representing a student in the simulation
installs = np.random.choice(issue_range, nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(installs)

# add calculation columnns
df['has_a_problem'] = df.sum(axis=1) > 0

# get mean of calculation True/False columns
# format and print results
problems = int(round(df['has_a_problem'].mean(),2) * 100)

print(f'The odds of a problem occuring in the first 150 instllations is {problems}%')

The odds of a problem occuring in the first 150 instllations is 45%


In [61]:
#How likely is it that 450 students all download anaconda without an issue?

nrows = 100_000 # set rows to number of simulations
ncols = 450      # set columns to number of students in each simulation

# list with 249 falses and one true
issue_range = [False for r in range(1,250)]
issue_range.append(True)

# create array with each row representing a simulation and each column representing a student in the simulation
installs = np.random.choice(issue_range, nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(installs)

# add calculation columnns
df['has_no_problem'] = df.sum(axis=1) == 0

# get mean of calculation True/False columns
# format and print results
problems = int(round(df['has_no_problem'].mean(),2) * 100)

print(f'The odds of 450 instllations occuring without an issue is {problems}%')

The odds of 450 instllations occuring without an issue is 16%


In [62]:
# 7) There's a 70% chance on any given day that there will be at least 
# one food truck at Travis Park. However, you haven't seen a food 
# truck there in 3 days. How unlikely is this?

nrows = 100_000 # set rows to number of simulations
ncols = 3      # set columns to represent 3 day without a food truck in each simulation



In [63]:
# create array with each row representing a simulation and each column representing a 3 days in the simulation
sightings = np.random.choice([True, False], nrows * ncols, p=[.7,.3]).reshape(nrows, ncols)
sightings


array([[ True,  True,  True],
       [ True, False,  True],
       [ True,  True, False],
       ...,
       [False, False,  True],
       [False, False,  True],
       [ True,  True,  True]])

In [64]:
df = pd.DataFrame(sightings)
df.head()


0      1      2
0  True   True   True
1  True  False   True
2  True   True  False
3  True   True   True
4  True  False  False

In [65]:
# add calculation columnns
df['times_sighted'] = df.sum(axis=1)
df['not_sighted_three_days'] = df.times_sighted == 0
df.head()

0      1      2  times_sighted  not_sighted_three_days
0  True   True   True              3                   False
1  True  False   True              2                   False
2  True   True  False              2                   False
3  True   True   True              3                   False
4  True  False  False              1                   False

In [66]:
df['not_sighted_three_days'].mean()


0.02642

In [67]:
# get mean of calculation True/False columns
trucks = int(round(df['not_sighted_three_days'].mean(),2) * 100)

print(f'The chance of not seeing a food truck in Travis Park for three days is {trucks}%')

The chance of not seeing a food truck in Travis Park for three days is 3%


In [96]:
# How likely is it that a food truck will show up sometime this week?

# Remaining week days
nrows = 100_000 # set rows to number of simulations
ncols = 2      # set columns to number of days in each simulation

# create array with each row representing a simulation and each column representing a student in the simulation
sightings = np.random.choice([True, False], nrows * ncols, p=[.7,.3]).reshape(nrows, ncols)

sightings


array([[ True,  True],
       [ True, False],
       [ True,  True],
       ...,
       [ True, False],
       [ True,  True],
       [ True, False]])

In [101]:
# add calculation columnns
sightings = df.sum(axis=1) > 3
df = pd.DataFrame(sightings)

In [102]:
# 8) If 23 people are in the same room, what are the odds that two of them share a birthday?
# What if it's 20 people? 40?

nrows = 100_000 # set rows to number of simulations
ncols = 23       # set columns to number of people in each simulation

birth_days = np.random.choice([r for r in range(366)], nrows * ncols).reshape(nrows, ncols)
birth_days


array([[317, 259,  92, ..., 271, 259, 248],
       [284, 108, 271, ..., 210, 359, 242],
       [176, 262, 284, ...,  90,  94,   0],
       ...,
       [ 56, 322,  61, ...,   2,  12, 295],
       [105, 251, 252, ...,  55,  77,  80],
       [341, 119, 340, ...,   5,  55,  12]])

In [103]:
df = pd.DataFrame(birth_days)
df.head()

0    1    2    3    4    5    6    7    8    9   ...   13   14   15   16  \
0  317  259   92  307  183   30   31  250  275  295  ...   48  169  361   23   
1  284  108  271  321   11  201  294   67   88  281  ...  266   50   45   38   
2  176  262  284  210  182  134  102  208  109  238  ...  146  145  162   53   
3  122  205  139   36  334  104  179  104  246   49  ...   93  309  354  298   
4  197  241  111   63   33  364  341   62  114  361  ...  130   39  266  283   

    17   18   19   20   21   22  
0  247  103  141  271  259  248  
1  231  305  251  210  359  242  
2  352  361  190   90   94    0  
3  129  356  324  352  323  362  
4  264  130  169  283   81  187  

[5 rows x 23 columns]

In [104]:
df['at_least_two_matching_birthdays'] = df.nunique(axis=1) < ncols
df['exactly_two_matching_birthdays'] = df.nunique(axis=1) == ncols-1
df.head()

0    1    2    3    4    5    6    7    8    9  ...   15   16   17   18  \
0  317  259   92  307  183   30   31  250  275  295  ...  361   23  247  103   
1  284  108  271  321   11  201  294   67   88  281  ...   45   38  231  305   
2  176  262  284  210  182  134  102  208  109  238  ...  162   53  352  361   
3  122  205  139   36  334  104  179  104  246   49  ...  354  298  129  356   
4  197  241  111   63   33  364  341   62  114  361  ...  266  283  264  130   

    19   20   21   22  at_least_two_matching_birthdays  \
0  141  271  259  248                             True   
1  251  210  359  242                            False   
2  190   90   94    0                            False   
3  324  352  323  362                             True   
4  169  283   81  187                             True   

   exactly_two_matching_birthdays  
0                           False  
1                           False  
2                           False  
3                           False  
4                            True  

[5 rows x 25 columns]

In [105]:
at_least_two_matching_birthdays = int(round(df['at_least_two_matching_birthdays'].mean(),2) * 100)
exactly_two_matching_birthdays = int(round(df['exactly_two_matching_birthdays'].mean(),2) * 100)

print(f'The odds of a room of {ncols} people having at least two people that share a birthday are {at_least_two_matching_birthdays}%')
print(f'The odds of a room of {ncols} people having exactly two people that share a birthday are {exactly_two_matching_birthdays}%')

The odds of a room of 23 people having at least two people that share a birthday are 51%
The odds of a room of 23 people having exactly two people that share a birthday are 13%


In [106]:
nrows = 100_000 # set rows to number of simulations
ncols = 20       # set columns to number of students in each simulation

# create array with each row representing a simulation and each column representing a student in the simulation
sightings = np.random.choice([r for r in range(366)], nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(sightings)

# add calculation columnns
df['at_least_two_matching_birthdays'] = df.nunique(axis=1) < ncols
df['exactly_two_matching_birthdays'] = df.nunique(axis=1) == ncols-1

# get mean of calculation True/False columns
# format and print results
at_least_two_matching_birthdays = int(round(df['at_least_two_matching_birthdays'].mean(),2) * 100)
exactly_two_matching_birthdays = int(round(df['exactly_two_matching_birthdays'].mean(),2) * 100)

print(f'The odds of a room of {ncols} people having at least two people that share a birthday are {at_least_two_matching_birthdays}%')
print(f'The odds of a room of {ncols} people having exactly least two people that share a birthday are {exactly_two_matching_birthdays}%')

The odds of a room of 20 people having at least two people that share a birthday are 41%
The odds of a room of 20 people having exactly least two people that share a birthday are 9%


In [107]:
nrows = 100_000 # set rows to number of simulations
ncols = 40       # set columns to number of students in each simulation

# create array with each row representing a simulation and each column representing a student in the simulation
sightings = np.random.choice([r for r in range(366)], nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(sightings)

# add calculation columnns
df['at_least_two_matching_birthdays'] = df.nunique(axis=1) < ncols
df['exactly_two_matching_birthdays'] = df.nunique(axis=1) == ncols-1

# get mean of calculation True/False columns
# format and print results
at_least_two_matching_birthdays = int(round(df['at_least_two_matching_birthdays'].mean(),2) * 100)
exactly_two_matching_birthdays = int(round(df['exactly_two_matching_birthdays'].mean(),2) * 100)

print(f'The odds of a room of {ncols} people having at least two people that share a birthday are {at_least_two_matching_birthdays}%')
print(f'The odds of a room of {ncols} people having exactly two people that share a birthday are {exactly_two_matching_birthdays}%')

The odds of a room of 40 people having at least two people that share a birthday are 89%
The odds of a room of 40 people having exactly two people that share a birthday are 28%
